import type { ReservationInterface } from '@/interfaces/ReservationInterface';

export const reservationSeeder: ReservationInterface[] = [
  {
    id: 1,
    restaurantId: 1,
    userId: 101,
    clientName: 'Valentina Restrepo',
    clientEmail: 'valentina.r@email.com',
    date: 'Hoy',
    time: '20:00',
    guests: 4,
    status: 'confirmed',
    specialRequest: 'Mesa cerca a la terraza, celebración de cumpleaños.',
  },
  {
    id: 2,
    restaurantId: 1,
    userId: 102,
    clientName: 'Carlos Mario Gómez',
    clientEmail: 'carlos.mario@email.com',
    date: 'Hoy',
    time: '20:30',
    guests: 2,
    status: 'pending',
    specialRequest: 'Una persona es vegetariana.',
  },
  {
    id: 3,
    restaurantId: 1,
    userId: 103,
    clientName: 'Mariana Duque',
    clientEmail: 'mariana.d@email.com',
    date: 'Mañana',
    time: '13:30',
    guests: 6,
    status: 'confirmed',
    specialRequest: 'Requiere silla para bebé.',
  },
  {
    id: 4,
    restaurantId: 1,
    userId: 104,
    clientName: 'Santiago Montoya',
    clientEmail: 'santiago.m@email.com',
    date: 'Mañana',
    time: '19:00',
    guests: 2,
    status: 'cancelled',
    specialRequest: 'Ninguna',
  },
  {
    id: 5,
    restaurantId: 1,
    userId: 105,
    clientName: 'Laura Ospina',
    clientEmail: 'laura.ospina@email.com',
    date: '2026-08-29',
    time: '21:00',
    guests: 3,
    status: 'completed',
    specialRequest: 'Mesa tranquila para reunión de negocios.',
  },
  {
    id: 6,
    restaurantId: 1,
    userId: 106,
    clientName: 'Alejandro Morales',
    clientEmail: 'alejandro.m@email.com',
    date: 'Hoy',
    time: '21:15',
    guests: 5,
    status: 'confirmed',
    specialRequest: 'Mesa exterior',
  },
  {
    id: 7,
    restaurantId: 1,
    userId: 107,
    clientName: 'Sofía Londoño',
    clientEmail: 'sofia.l@email.com',
    date: 'Mañana',
    time: '20:00',
    guests: 3,
    status: 'pending',
    specialRequest: 'Silla para niño',
  },
];
