import type { RestaurantInterface } from '@/interfaces/RestaurantInterface';

export const restaurantSeedData: RestaurantInterface[] = [
  {
    id: 1,
    name: 'La Trattoria Di Roma',
    address: 'Cra 7 #67-29',
    city: 'Bogotá',
    category: 'Italiana',
    priceLevel: 3,
    latitude: 4.6502,
    longitude: -74.0608,
    adminId: 1,
    description: 'Auténtica pasta artesanal y pizzas al horno de leña.',
    imageUrl:
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    reviewCount: 128,
    status: 'active',
  },
  {
    id: 2,
    name: 'Cantina Los Compadres',
    address: 'Calle 10 #35-12',
    city: 'Medellín',
    category: 'Mexicana',
    priceLevel: 2,
    latitude: 6.2079,
    longitude: -75.5675,
    adminId: 2,
    description: 'Sabores tradicionales mexicanos y coctelería.',
    imageUrl:
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    reviewCount: 94,
    status: 'active',
  },
  {
    id: 3,
    name: 'Sakura Sushi Bar',
    address: 'Av. San Martín #8-45',
    city: 'Cartagena',
    category: 'Japonesa',
    priceLevel: 4,
    latitude: 10.3997,
    longitude: -75.5582,
    adminId: 3,
    description: 'Sushi fresco de alta gama y platos nikkei.',
    imageUrl:
      'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviewCount: 210,
    status: 'active',
  },
  {
    id: 4,
    name: 'Fuego Criollo Asador',
    address: 'Av. 9 Norte #14-20',
    city: 'Cali',
    category: 'Colombiana',
    priceLevel: 3,
    latitude: 3.4644,
    longitude: -76.5305,
    adminId: 4,
    description: 'Cortes premium a la brasa y comida típica.',
    imageUrl:
      'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    reviewCount: 165,
    status: 'active',
  },
  {
    id: 5,
    name: 'Olea Cocina Mediterránea',
    address: 'Calle 85 #12-50',
    city: 'Bogotá',
    category: 'Mediterránea',
    priceLevel: 4,
    latitude: 4.6709,
    longitude: -74.0541,
    adminId: 5,
    description: 'Tapas, arroces y pescados frescos con aceite de oliva extra virgen.',
    imageUrl:
      'https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    reviewCount: 88,
    status: 'active',
  },
  {
    id: 6,
    name: 'Nikkei & Co. Fusión',
    address: 'Carrera 43A #1-50',
    city: 'Medellín',
    category: 'Fusión',
    priceLevel: 4,
    latitude: 6.2033,
    longitude: -75.5736,
    adminId: 6,
    description: 'Innovadora mezcla peruano-japonesa con ingredientes locales.',
    imageUrl:
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviewCount: 142,
    status: 'active',
  },
];
