import type { RestaurantInterface } from '@/interfaces/RestaurantInterface';

export const restaurantSeeder: RestaurantInterface[] = [
  {
    id: 1,
    name: 'La Trattoria Di Roma',
    address: 'Cra 7 #67-29',
    city: 'Bogotá',
    category: 'Italiana',
    averagePrice: 3,
    latitude: 4.6502,
    longitude: -74.0608,
    adminId: 1,
    description: 'Auténtica pasta artesanal y pizzas al horno de leña.',
    imageUrl:
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    status: 'active',
  },
  {
    id: 2,
    name: 'Cantina Los Compadres',
    address: 'Calle 10 #35-12',
    city: 'Medellín',
    category: 'Mexicana',
    averagePrice: 2,
    latitude: 6.2079,
    longitude: -75.5675,
    adminId: 2,
    description: 'Sabores tradicionales mexicanos y coctelería.',
    imageUrl:
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
    status: 'active',
  },
  {
    id: 3,
    name: 'Sakura Sushi Bar',
    address: 'Av. San Martín #8-45',
    city: 'Cartagena',
    category: 'Japonesa',
    averagePrice: 4,
    latitude: 10.3997,
    longitude: -75.5582,
    adminId: 3,
    description: 'Sushi fresco de alta gama y platos nikkei.',
    imageUrl:
      'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80',
    status: 'active',
  },
  {
    id: 4,
    name: 'Fuego Criollo Asador',
    address: 'Av. 9 Norte #14-20',
    city: 'Cali',
    category: 'Colombiana',
    averagePrice: 3,
    latitude: 3.4644,
    longitude: -76.5305,
    adminId: 4,
    description: 'Cortes premium a la brasa y comida típica.',
    imageUrl:
      'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    status: 'active',
  },
  {
    id: 5,
    name: 'Olea Cocina Mediterránea',
    address: 'Calle 85 #12-50',
    city: 'Bogotá',
    category: 'Mediterránea',
    averagePrice: 4,
    latitude: 4.6709,
    longitude: -74.0541,
    adminId: 5,
    description: 'Tapas, arroces y pescados frescos con aceite de oliva extra virgen.',
    imageUrl:
      'https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?auto=format&fit=crop&w=800&q=80',
    status: 'active',
  },
  {
    id: 6,
    name: 'Nikkei & Co. Fusión',
    address: 'Carrera 43A #1-50',
    city: 'Medellín',
    category: 'Fusión',
    averagePrice: 4,
    latitude: 6.2033,
    longitude: -75.5736,
    adminId: 6,
    description: 'Innovadora mezcla peruano-japonesa con ingredientes locales.',
    imageUrl:
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    status: 'active',
  },
  {
    id: 7,
    name: 'Elcielo',
    address: 'Cl. 7D #43c-36, El Poblado',
    city: 'Medellín',
    category: 'Fusión',
    averagePrice: 5,
    latitude: 6.207,
    longitude: -75.567,
    adminId: 7,
    description: 'Experiencia gastronómica sensorial y creativa.',
    imageUrl: 'https://elcielo.com.co/wp-content/uploads/2025/08/the-experience.webp',
    status: 'active',
  },
  {
    id: 8,
    name: 'Carmen Medellín',
    address: 'Cra. 36 #10a-27, El Poblado',
    city: 'Medellín',
    category: 'Contemporánea',
    averagePrice: 5,
    latitude: 6.2085,
    longitude: -75.565,
    adminId: 8,
    description: 'Sabores locales con técnicas modernas en un ambiente elegante.',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCOSgTvjESain2lcef2wAlDQb22BSGzojIvyYfnKnpuQ&s=10',
    status: 'active',
  },
  {
    id: 9,
    name: 'Alambique',
    address: 'Cl. 10 #43a-30, El Poblado',
    city: 'Medellín',
    category: 'Colombiana',
    averagePrice: 3,
    latitude: 6.209,
    longitude: -75.5685,
    adminId: 9,
    description: 'Laboratorio gastronómico de comida tradicional con un toque rústico.',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAKOsSFZUAGKZGs6tzk5rE3d9x7eVjG-wfREUI4qQ-Yw&s=10',
    status: 'active',
  },
  {
    id: 10,
    name: "Restaurante Mondongo's",
    address: 'Cl. 10 #38-38, El Poblado',
    city: 'Medellín',
    category: 'Colombiana',
    averagePrice: 2,
    latitude: 6.2095,
    longitude: -75.5665,
    adminId: 10,
    description: 'El sabor tradicional de Antioquia, famoso por su mondongo.',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRihLEQ-RiU6AthTN133X0Ota0BZTtovM7naAs_BgN_dg&s=10',
    status: 'active',
  },
  {
    id: 11,
    name: 'Colosal Restaurante',
    address: 'Cl. 16a Sur #9F-13, Casaloma',
    city: 'Medellín',
    category: 'Fusión',
    averagePrice: 4,
    latitude: 6.195,
    longitude: -75.56,
    adminId: 11,
    description: 'Restaurante con vista espectacular y comida de autor.',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSe3UduExibTGEsbYczIzpeob5Oi9k5p19XO401QldL9g&s=10',
    status: 'active',
  },
];
