import type { UserInterface } from '@/interfaces/UserInterface';

export const userSeeder: UserInterface[] = [
  {
    id: 1,
    name: 'Admin Reservia',
    email: 'admin@reservia.com',
    phone: '555-000-1111',
    password: 'password123',
    role: 'admin',
    status: 'active',
  },
  {
    id: 2,
    name: 'Cliente Prueba',
    email: 'cliente@reservia.com',
    phone: '555-000-2222',
    password: 'password123',
    role: 'client',
    status: 'active',
  },
  {
    id: 101,
    name: 'Valentina Restrepo',
    email: 'valentina.r@email.com',
    phone: '555-000-0101',
    password: 'password123',
    role: 'client',
    status: 'active',
  },
  {
    id: 102,
    name: 'Carlos Mario Gómez',
    email: 'carlos.mario@email.com',
    phone: '555-000-0102',
    password: 'password123',
    role: 'client',
    status: 'active',
  },
  {
    id: 103,
    name: 'Mariana Duque',
    email: 'mariana.d@email.com',
    phone: '555-000-0103',
    password: 'password123',
    role: 'client',
    status: 'active',
  },
  {
    id: 104,
    name: 'Santiago Montoya',
    email: 'santiago.m@email.com',
    phone: '555-000-0104',
    password: 'password123',
    role: 'client',
    status: 'active',
  },
  {
    id: 105,
    name: 'Laura Ospina',
    email: 'laura.ospina@email.com',
    phone: '555-000-0105',
    password: 'password123',
    role: 'client',
    status: 'active',
  },
  {
    id: 106,
    name: 'Alejandro Morales',
    email: 'alejandro.m@email.com',
    phone: '555-000-0106',
    password: 'password123',
    role: 'client',
    status: 'active',
  },
  {
    id: 107,
    name: 'Sofía Londoño',
    email: 'sofia.l@email.com',
    phone: '555-000-0107',
    password: 'password123',
    role: 'client',
    status: 'active',
  },
  {
    id: 108,
    name: 'Mateo Correa',
    email: 'mateo.correa@email.com',
    phone: '555-000-0108',
    password: 'password123',
    role: 'client',
    status: 'active',
  },
  {
    id: 109,
    name: 'Camila Rojas',
    email: 'camila.rojas@email.com',
    phone: '555-000-0109',
    password: 'password123',
    role: 'client',
    status: 'active',
  },
  {
    id: 110,
    name: 'Daniel Vélez',
    email: 'daniel.velez@email.com',
    phone: '555-000-0110',
    password: 'password123',
    role: 'client',
    status: 'active',
  },
];
